---
title: "Model Establishment for WMT Stock"
author: "group project"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Testing ARCH Effects
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(TSA)
library(xts)
library(xtable)
library(lubridate)
library(readxl)
AMZN <- read_excel("F:/CUEB/Junior/SPRING/FDA/FDA_project_group_XN/data/WMT.xlsx",col_types = c("date", "numeric", "numeric", "numeric", "numeric", "numeric"))
load("D:/Senior/FDA/学期小组作业/FDA_project_group_XN/data/WMT_all.RData")
AMZN = AMZN[-1763:-1764,]
lgreturn = diff(log(WMT$close))*100

at = lgreturn-mean(lgreturn)
Box.test(at^2,lag=5,type='Ljung') # perform a Ljung Box test to test ARCH effects
```

## Time plots of the stock price and trading volume
```{r, echo=TRUE, message=FALSE, warning=FALSE}

plot(col='blue',y=WMT$close,x=WMT$date,xlab='year', ylab='volume',type='l',main='Stock Price of WMT 2010-2016')

plot(col='brown',y=WMT$volume,x=WMT$date,xlab='year', ylab='volume',type='l',main='Trading Volume of WMT 2010-2016')

```

## GARCH Modelling
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(fGarch)

#norm innovation
m1 = garchFit(~ garch(4,0), data = lgreturn, cond.dist = "norm") # Fit an ARCH(4) model
summary(m1)

m2 = garchFit(~ garch(1,1), data = lgreturn, cond.dist = "norm") # Fit a GARCH(1,1) model
summary(m2)

#t innovation
m11=garchFit(~ garch(4,0), data = lgreturn, cond.dist = "std") # Fit an ARCH(4) model
summary(m11)

m22 = garchFit(~ garch(1,1), data = lgreturn, cond.dist = "std") # Fit a GARCH(1,1) model 
summary(m22)
```

## Plot the estimated volatility and standardized residuals based on the selected model
```{r, echo=TRUE, message=FALSE, warning=FALSE}
vol_1 <- fBasics::volatility(m1)
plot(col='purple',y=vol_1,x=WMT$date,xlab='year', ylab='volatility of WMT',type='l',main='Volatility of WMT 2010-2016')

sres_1 <- residuals(m1, standardize=TRUE)
plot(col='blue',y=sres_1,x=WMT$date,xlab='year', ylab='standardized residuals of WMT',type='l',main='standardized residuals of WMT 2010-2016')

```

## Predict
```{r, echo=TRUE, message=FALSE, warning=FALSE}
load("D:/Senior/FDA/学期小组作业/WMT2017.RData")
logreturn2017 = diff(log(WMT2017$close))*100
print(logreturn2017)
sigma2=predict(m1,114)
print(sigma2)
library(sciplot)
plot(sigma2$meanForecast,ylim=c(-3.0,3.0),type = "l")
lines(c(1:114),logreturn2017,col='red')
lines(c(1:50),sigma2$meanForecast+1.96*sigma2$meanError,col='blue')
lines(c(1:50),sigma2$meanForecast-1.96*sigma2$meanError,col='blue')
```
